// Generated by CoffeeScript 1.12.5

/*
  Copyright (c) 2014 clowwindy
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
 */

(function() {
  var EVP_BytesToKey, Encryptor, bytes_to_key_results, create_rc4_md5_cipher, crypto, encryptAll, int32Max, method_supported, util;

  crypto = require("crypto");

  util = require("util");

  int32Max = Math.pow(2, 32);

  bytes_to_key_results = {};

  EVP_BytesToKey = function(password, key_len, iv_len) {
    var count, d, data, i, iv, key, m, md5, ms;
    if (bytes_to_key_results[password + ":" + key_len + ":" + iv_len]) {
      return bytes_to_key_results[password + ":" + key_len + ":" + iv_len];
    }
    m = [];
    i = 0;
    count = 0;
    while (count < key_len + iv_len) {
      md5 = crypto.createHash('md5');
      data = password;
      if (i > 0) {
        data = Buffer.concat([m[i - 1], password]);
      }
      md5.update(data);
      d = md5.digest();
      m.push(d);
      count += d.length;
      i += 1;
    }
    ms = Buffer.concat(m);
    key = ms.slice(0, key_len);
    iv = ms.slice(key_len, key_len + iv_len);
    bytes_to_key_results[password] = [key, iv];
    return [key, iv];
  };

  method_supported = {
    'aes-128-cfb': [16, 16],
    'aes-256-cfb': [32, 16],
    'aes-128-ctr': [16, 16],
    'aes-256-ctr': [32, 16],
    'rc4-md5': [16, 16]
  };

  create_rc4_md5_cipher = function(key, iv, op) {
    var md5, rc4_key;
    md5 = crypto.createHash('md5');
    md5.update(key);
    md5.update(iv);
    rc4_key = md5.digest();
    if (op === 1) {
      return crypto.createCipheriv('rc4', rc4_key, '');
    } else {
      return crypto.createDecipheriv('rc4', rc4_key, '');
    }
  };

  Encryptor = (function() {
    function Encryptor(key1, method1) {
      this.key = key1;
      this.method = method1;
      this.iv_sent = false;
      this.cipher = this.get_cipher(this.key, this.method, 1, crypto.randomBytes(32));
    }

    Encryptor.prototype.get_cipher_len = function(method) {
      var m;
      method = method.toLowerCase();
      m = method_supported[method];
      return m;
    };

    Encryptor.prototype.get_cipher = function(password, method, op, iv) {
      var iv_, key, m, ref;
      method = method.toLowerCase();
      password = new Buffer(password, 'binary');
      m = this.get_cipher_len(method);
      if (m != null) {
        ref = EVP_BytesToKey(password, m[0], m[1]), key = ref[0], iv_ = ref[1];
        if (iv == null) {
          iv = iv_;
        }
        if (op === 1) {
          this.cipher_iv = iv.slice(0, m[1]);
        }
        iv = iv.slice(0, m[1]);
        if (method === 'rc4-md5') {
          return create_rc4_md5_cipher(key, iv, op);
        } else {
          if (op === 1) {
            return crypto.createCipheriv(method, key, iv);
          } else {
            return crypto.createDecipheriv(method, key, iv);
          }
        }
      }
    };

    Encryptor.prototype.encrypt = function(buf) {
      var result;
      result = this.cipher.update(buf);
      if (this.iv_sent) {
        return result;
      } else {
        this.iv_sent = true;
        return Buffer.concat([this.cipher_iv, result]);
      }
    };

    Encryptor.prototype.decrypt = function(buf) {
      var decipher_iv, decipher_iv_len, result;
      if (this.decipher == null) {
        decipher_iv_len = this.get_cipher_len(this.method)[1];
        decipher_iv = buf.slice(0, decipher_iv_len);
        this.decipher = this.get_cipher(this.key, this.method, 0, decipher_iv);
        result = this.decipher.update(buf.slice(decipher_iv_len));
        return result;
      } else {
        result = this.decipher.update(buf);
        return result;
      }
    };

    return Encryptor;

  })();

  encryptAll = function(password, method, op, data) {
    var cipher, iv, ivLen, iv_, key, keyLen, ref, ref1, result;
    result = [];
    method = method.toLowerCase();
    ref = method_supported[method], keyLen = ref[0], ivLen = ref[1];
    password = Buffer(password, 'binary');
    ref1 = EVP_BytesToKey(password, keyLen, ivLen), key = ref1[0], iv_ = ref1[1];
    if (op === 1) {
      iv = crypto.randomBytes(ivLen);
      result.push(iv);
    } else {
      iv = data.slice(0, ivLen);
      data = data.slice(ivLen);
    }
    if (method === 'rc4-md5') {
      cipher = create_rc4_md5_cipher(key, iv, op);
    } else {
      if (op === 1) {
        cipher = crypto.createCipheriv(method, key, iv);
      } else {
        cipher = crypto.createDecipheriv(method, key, iv);
      }
    }
    result.push(cipher.update(data));
    result.push(cipher.final());
    return Buffer.concat(result);
  };

  exports.Encryptor = Encryptor;

  exports.encryptAll = encryptAll;

}).call(this);
